### ISSUE TITLE
Feat: Audio as an input

### ISSUE THREAD

**Issue by ChakshuGautam** [AmakrushAI/app#2] opened 2023-04-01 05:52 UTC
- [ ] Allow for the recording of audio on the frontend
- [ ] Stream audio to transport socket and build a complete audio file => Save it to S3
- [ ] Send the audio file stream to the BFF for further analysis

**Comment by prtkjakhar** [comment] 2023-04-18 06:40
Duplicate of #15

**Closed** 2023-04-18 06:42 UTC
Labels: App
